"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Wand2, CheckCircle2 } from "lucide-react"
import { useFormatCurrency } from "@/lib/i18n/formatCurrency"

type Proposal = {
  id: string
  cycle_date: string
  amount: number
  bills_amount: number
  debts_amount: number
  goals_amount: number
  flexible_amount: number
  status: "pending" | "approved" | "dismissed"
} | null

type Props = {
  proposal: Proposal
}

function formatDate(iso: string): string {
  return new Date(iso + "T00:00:00").toLocaleDateString("en-US", { month: "long", day: "numeric" })
}

/**
 * Plan Autopilot -- the breakdown shown here is fully derived from real
 * bills/debts/goals (lib/paycheckAutopilot.ts, generated by the cron in
 * app/api/cron/paycheck-autopilot/route.ts a few days before the predicted
 * payday). "Approve" is an acknowledgment, not a mutation -- there's no
 * separate persisted budget for it to write into, same reasoning as
 * StrengthenPaycheckPanel's preview-only suggestions.
 */
export default function PaycheckAutopilotView({ proposal }: Props) {
  const formatMoney = useFormatCurrency()
  const router = useRouter()
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const header = (
    <div className="flex items-center gap-3">
      <span className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-500/15 border border-emerald-500/30">
        <Wand2 size={22} className="text-emerald-400" />
      </span>
      <div>
        <h1 className="text-2xl font-bold text-white">Plan Autopilot</h1>
        <p className="text-sm text-gray-400">Your next paycheck plan, drafted before it arrives.</p>
      </div>
    </div>
  )

  if (!proposal) {
    return (
      <div className="space-y-8">
        {header}
        <p className="text-gray-400">
          Nothing drafted yet. A few days before your next predicted payday, Autopilot will draft what that paycheck
          needs to cover -- based on your real bills, debts, and goals -- and you'll see it here.
        </p>
      </div>
    )
  }

  const committed = proposal.bills_amount + proposal.debts_amount + proposal.goals_amount

  async function decide(status: "approved" | "dismissed") {
    setSubmitting(true)
    setError(null)
    try {
      const res = await fetch("/api/paycheck-autopilot/decide", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ proposalId: proposal!.id, status }),
      })
      const data = await res.json().catch(() => null)
      if (!res.ok || !data?.ok) {
        setError((data && data.error) || "Something went wrong -- try again.")
        return
      }
      router.refresh()
    } catch {
      setError("Something went wrong -- try again.")
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="space-y-8">
      {header}

      <div className="rounded-2xl border border-gray-700 bg-gradient-to-br from-[#0f172a] to-[#0b1220] p-6 shadow-lg">
        <p className="text-sm text-gray-400">Expected {formatDate(proposal.cycle_date)}</p>
        <p className="mt-1 text-4xl font-bold text-white">{formatMoney(proposal.amount)}</p>

        <div className="mt-5 space-y-1.5 text-sm">
          <div className="flex justify-between text-gray-400">
            <span>Bills</span>
            <span className="text-gray-200">{formatMoney(proposal.bills_amount)}</span>
          </div>
          <div className="flex justify-between text-gray-400">
            <span>Debt</span>
            <span className="text-gray-200">{formatMoney(proposal.debts_amount)}</span>
          </div>
          <div className="flex justify-between text-gray-400">
            <span>Goals</span>
            <span className="text-gray-200">{formatMoney(proposal.goals_amount)}</span>
          </div>
          <div className="flex justify-between border-t border-gray-800 pt-1.5 text-gray-400">
            <span>Committed</span>
            <span className="text-gray-200">{formatMoney(committed)}</span>
          </div>
          <div className="flex justify-between font-semibold">
            <span className="text-gray-300">Flexible</span>
            <span className={proposal.flexible_amount >= 0 ? "text-emerald-400" : "text-red-400"}>
              {formatMoney(proposal.flexible_amount)}
            </span>
          </div>
        </div>
      </div>

      {proposal.status === "pending" && (
        <div>
          {error && <p className="mb-3 text-sm text-red-400">{error}</p>}
          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => decide("approved")}
              disabled={submitting}
              className="rounded-lg bg-emerald-500 px-5 py-2 font-semibold text-black disabled:opacity-60"
            >
              Approve plan
            </button>
            <button
              type="button"
              onClick={() => decide("dismissed")}
              disabled={submitting}
              className="rounded-lg border border-gray-700 px-5 py-2 font-semibold text-gray-300 hover:bg-white/5 disabled:opacity-60"
            >
              Dismiss
            </button>
          </div>
        </div>
      )}

      {proposal.status === "approved" && (
        <p className="flex items-center gap-2 text-sm text-emerald-400">
          <CheckCircle2 size={16} /> Approved -- you're set for this paycheck.
        </p>
      )}
      {proposal.status === "dismissed" && <p className="text-sm text-gray-500">Dismissed.</p>}
    </div>
  )
}
